version: 0.0
os: linux
files:
  - source: /website/index.php
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: website/scripts/clean_dir.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: website/scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: website/scripts/stop_server.sh
      timeout: 300
      runas: root